version: '3'

services:
  selenium-hub:
    image: selenium/hub:4.0.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome-node:
    build: .
    environment:
      - HUB_HOST=selenium-hub
    depends_on:
      - selenium-hub